import type { Metadata } from "next";
import "./globals.css"; // Ensure global CSS is applied
import Header from "./component/header";
import Footer from "./component/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased"> {/* Removed custom fonts */}
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
